# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Title of Blog Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Longer description of site. Edit this in _config.yml. Used exclusively by
  jekyll-seo-tag plugin (which is loaded by default 
  thanks to Minima theme, from which minimag inherits) and, as a result, this
  description will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

description_for_display: >- # this means to ignore newlines until an outdent
  This is the coolest site for things that it does and for those who want to
  visit it.

############### url and base url
# See https://mademistakes.com/mastering-jekyll/site-url-baseurl/

# url: the base hostname & protocol for your site, e.g. http://example.com
#   In particular, do NOT include a trailing forward slash.
url: "https://chess-spyder.github.io" 

# baseurl: the subpath of your site
#   Not needed for many sites and can be omitted
#   Necessary only when hosting site in a subdirectory. This is common when hosting
#   a project site on GitHub Pages, in which case:
#     baseurl: "/repo-name"
baseurl: "/jekyll-minimag" 

url_images: "/assets/images"
url_post_images: "/assets/images/posts"

twitter_username: fictitious
github_username:  fictitious

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

################
# Front-matter defaults

# Sets all posts by default to have layout _layouts/post.html
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# Permalink default
permalink: /:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
